### ISSUE TITLE
Installation on Synology? - is it possible?

### ISSUE THREAD

**Issue by wlcina** [DragonPrime/Legend-of-the-Green-Dragon#28]
Any chance to get this working on Synology?

**Comment by stephenKise** [comment]
What is Synology?

**Comment by wlcina** [comment]
Synology is NAS storage with some variation linux OS, can acts as webserver.  There are lot of packages EG wordpress etc. I already have installed Apache and PHP 7 and Maria db 10 on it (last one is not shown), but I dont know what to do next ;-) I understand it is out of support, but maybe someone who is reading issues can help.

![image](https://user-images.githubusercontent.com/35777945/44381324-0fec3c00-a510-11e8-981e-6c27f3eae090.png)

**Comment by stephenKise** [comment]
Well I am sorry to tell you that I don't have access to a NAS to give you a step-by-step guide on how to install LotGD there. In theory, you should be able to just drop in the files to the root directory and load up the local ip (192.168.x.x:80) if it is forwarded. I would check the Apache config to see where the files are being served from. If it has a terminal, the installation should be similar to what is already in the README. Good luck with getting it set up, I am sorry that I cannot assist too much. If you could, please document any solution you come across to help those who drop by in the future. :)

**Comment by bornhaeusser** [comment]
yes it works on synology. run it on a synology.

**Comment by wlcina** [comment]
Bornhausser may I ask you for simple step by step guide, I am newbie and I am afraid that I will do something irreversible on my syno :-(  Thank you in advance.

**Comment by bornhaeusser** [comment]
that is quiet easy.

-Webstation
-Apache
-nginx (optional)
-PHP 5 and 7
-myphpadmin

you should install all that package

then a web folder should be there in the synology explorer visible.
make. copy now all the lotgd files in a folder under the webfolder.

maka a database and db user (i make this always over phpmyadmin)
install the lotgd and follow all the setps in the lotgd web setup.
(could be possible to set some folders read/write - that you can manage with the synology explorer - httpuser/httpgroup should give that permission)

Hope this helps a bit.

**Comment by wlcina** [comment]
Thanks a lot, I will try it when I will be at home!

**Comment by DonaldTsang** [comment]
Does this run on a QNAP though (TS-1635-AX to be exact)? That is another question.
